name: Check Command Line Reference

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  check-cmdline-ref:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev
      
      - name: Setup
        uses: ./.github/actions/common-setup
        with:
          os: linux
          compiler: gcc
          platform: x86_64
          config: release
          build-llvm: true
      
      - name: Build Slang
        run: |
          cmake --preset default --fresh \
            -DSLANG_SLANG_LLVM_FLAVOR=USE_SYSTEM_LLVM \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=true
          cmake --workflow --preset release
      
      - name: Check command line reference docs
        run: |
          bin_dir=$(realpath ./build/bin/release)
          "$bin_dir/slangc" -help-style markdown -h > docs/command-line-slangc-reference.new.md
          if ! diff -u docs/command-line-slangc-reference.md docs/command-line-slangc-reference.new.md; then
            echo "::error::Command Line Reference documentation (docs/command-line-slangc-reference.md) is out of date. Please regenerate it using: slangc -help-style markdown -h"
            exit 1
          fi
          rm docs/command-line-slangc-reference.new.md 